// Code generated by protoc-gen-go. DO NOT EDIT.
// source: partition.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PartitionRequest struct {
	SiteId               string   `protobuf:"bytes,1,opt,name=siteId,proto3" json:"siteId,omitempty"`
	Seq                  uint32   `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PartitionRequest) Reset()         { *m = PartitionRequest{} }
func (m *PartitionRequest) String() string { return proto.CompactTextString(m) }
func (*PartitionRequest) ProtoMessage()    {}
func (*PartitionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_12ead894473a209c, []int{0}
}

func (m *PartitionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartitionRequest.Unmarshal(m, b)
}
func (m *PartitionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartitionRequest.Marshal(b, m, deterministic)
}
func (m *PartitionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartitionRequest.Merge(m, src)
}
func (m *PartitionRequest) XXX_Size() int {
	return xxx_messageInfo_PartitionRequest.Size(m)
}
func (m *PartitionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PartitionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PartitionRequest proto.InternalMessageInfo

func (m *PartitionRequest) GetSiteId() string {
	if m != nil {
		return m.SiteId
	}
	return ""
}

func (m *PartitionRequest) GetSeq() uint32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

type PartitionResponse struct {
	PartitionId          string   `protobuf:"bytes,1,opt,name=partitionId,proto3" json:"partitionId,omitempty"`
	Seq                  uint32   `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Status               bool     `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PartitionResponse) Reset()         { *m = PartitionResponse{} }
func (m *PartitionResponse) String() string { return proto.CompactTextString(m) }
func (*PartitionResponse) ProtoMessage()    {}
func (*PartitionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_12ead894473a209c, []int{1}
}

func (m *PartitionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartitionResponse.Unmarshal(m, b)
}
func (m *PartitionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartitionResponse.Marshal(b, m, deterministic)
}
func (m *PartitionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartitionResponse.Merge(m, src)
}
func (m *PartitionResponse) XXX_Size() int {
	return xxx_messageInfo_PartitionResponse.Size(m)
}
func (m *PartitionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PartitionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PartitionResponse proto.InternalMessageInfo

func (m *PartitionResponse) GetPartitionId() string {
	if m != nil {
		return m.PartitionId
	}
	return ""
}

func (m *PartitionResponse) GetSeq() uint32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *PartitionResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*PartitionRequest)(nil), "main.PartitionRequest")
	proto.RegisterType((*PartitionResponse)(nil), "main.PartitionResponse")
}

func init() { proto.RegisterFile("partition.proto", fileDescriptor_12ead894473a209c) }

var fileDescriptor_12ead894473a209c = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x48, 0x2c, 0x2a,
	0xc9, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc,
	0xcc, 0x53, 0xb2, 0xe1, 0x12, 0x08, 0x80, 0x49, 0x04, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08,
	0x89, 0x71, 0xb1, 0x15, 0x67, 0x96, 0xa4, 0x7a, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06,
	0x41, 0x79, 0x42, 0x02, 0x5c, 0xcc, 0xc5, 0xa9, 0x85, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xbc, 0x41,
	0x20, 0xa6, 0x52, 0x3c, 0x97, 0x20, 0x92, 0xee, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x05,
	0x2e, 0x6e, 0xb8, 0x5d, 0x70, 0x33, 0x90, 0x85, 0x30, 0x0d, 0x02, 0x5b, 0x59, 0x92, 0x58, 0x52,
	0x5a, 0x2c, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x11, 0x04, 0xe5, 0x25, 0xb1, 0x81, 0xdd, 0x6a, 0x0c,
	0x08, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x4b, 0xe3, 0xee, 0xbe, 0x00, 0x00, 0x00,
}
